{% set version = "4.8.5" %}
{% set libgfortran_version = [3, 0, 0] %}
{% set max_libgfortran_version = "4.0.0.a0" %}
{% set libquadmath_version = [0, 0, 0] %}
{% set libgcc_s_version = [1, 0, 0] %}
{% set chost = macos_machine %}

package:
  name: gfortran_impl_osx-64
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/gcc/gcc-{{ version }}/gcc-{{ version }}.tar.gz
  sha256: fa06e455ca198ddc11ea4ddf2a394cf7cfb66aa7e0ab98cc1184189f1d405870
  patches:
    - libgcc_macosx_min_version.patch

build:
  number: 9
  skip: True  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - libiconv
    - zlib
    - gmp
    - mpfr
    - isl
    - mpc

outputs:
  - name: libgfortran
    version: {{ libversion }}
    files:
      - lib/libgfortran.dylib
      - lib/libgfortran.{{ libgfortran_version[0] }}.dylib
      - lib/libgomp.dylib
      - lib/libgomp.{{ libgcc_s_version[0] }}.dylib

      # Including libquadmath for the time
      # being. This will need to be broken
      # out in the long term.
      - lib/libquadmath.dylib
      - lib/libquadmath.{{ libquadmath_version[0] }}.dylib

      # Including libgcc_s for the time
      # being. This will need to be broken
      # out in the long term.
      - lib/libgcc_s.{{ libgcc_s_version[0] }}.dylib
      - lib/libgcc_s_ppc64.{{ libgcc_s_version[0] }}.dylib
      - lib/libgcc_s_x86_64.{{ libgcc_s_version[0] }}.dylib

    run_exports:
      - libgfortran >={{ libversion }},<{{ max_libgfortran_version }}
    test:
      commands:
        - test -f "${PREFIX}/lib/libgfortran.dylib"
        - test -f "${PREFIX}/lib/libgfortran.{{ libgfortran_version[0] }}.dylib"

        - test -f "${PREFIX}/lib/libgomp.dylib"
        - test -f "${PREFIX}/lib/libgomp.{{ libgcc_s_version[0] }}.dylib"

        - test -f "${PREFIX}/lib/libquadmath.dylib"
        - test -f "${PREFIX}/lib/libquadmath.{{ libquadmath_version[0] }}.dylib"

        - test -f "${PREFIX}/lib/libgcc_s.{{ libgcc_s_version[0] }}.dylib"
        - test -f "${PREFIX}/lib/libgcc_s_ppc64.{{ libgcc_s_version[0] }}.dylib"
        - test -f "${PREFIX}/lib/libgcc_s_x86_64.{{ libgcc_s_version[0] }}.dylib"

  - name: gfortran_impl_osx-64
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - libiconv
        - zlib
        - gmp
        - mpfr
        - isl
        - mpc
      run:
        - libgfortran >={{ libversion }},<{{ max_libgfortran_version }}
        - isl
        - mpfr
        - mpc
        - gmp
        - zlib
        - libiconv
    files:
      - bin/gfortran
      - bin/{{ chost }}-gfortran

      - libexec/gcc/{{ chost }}/{{ version }}/collect2
      - libexec/gcc/{{ chost }}/{{ version }}/f951
      - libexec/gcc/{{ chost }}/{{ version }}/lto-wrapper

      - lib/libgfortran.spec

      # For -fopenmp
      - lib/libgomp.spec

      # For -ffast-math
      - lib/gcc/{{ chost }}/{{ version }}/crtfastmath.o

      # For -static
      - lib/libgfortran.a
      - lib/libgomp.a

      - lib/gcc/{{ chost }}/{{ version }}/libgcc.a
      - lib/gcc/{{ chost }}/{{ version }}/libgcc_eh.a

      - lib/gcc/{{ chost }}/{{ version }}/finclude/**

      # include{,-fixed} may not be needed unless -fopenmp is passed (not sure on that)
      - lib/gcc/{{ chost }}/{{ version }}/include-fixed/**
      - lib/gcc/{{ chost }}/{{ version }}/include/**

      # Stub libraries
      - lib/libgcc_ext.10.4.dylib
      - lib/libgcc_ext.10.5.dylib

    test:
      script: run_test.sh

about:
  home: http://gcc.gnu.org/
  license: GPL 3 (with GCC Runtime Library Exception 3.1)
  license_family: GPL
  license_file: COPYING3
  summary: Fortran compiler and libraries from the GNU Compiler Collection

extra:
  recipe-maintainers:
    - beckermr
    - isuruf
