{% set chost = macos_machine %}
{% set build_number = 26 %}
{% set version_suffix = "" %}

{% if gfortran_version is undefined %}
{% set gfortran_version = "7.5.0" %}
{% endif %}

{% if gfortran_version == "7.5.0" %}
{% set libgfortran_version = "4.0.0" %}
{% set max_libgfortran_version = "5.0.0.a0" %}
{% set libgfortran_major_version = "4" %}
{% set source_sha = "4f518f18cfb694ad7975064e99e200fe98af13603b47e67e801ba9580e50a07f" %}
{% set url = "https://ftp.gnu.org/gnu/gcc/gcc-7.5.0/gcc-7.5.0.tar.gz" %}
{% endif %}

{% if gfortran_version == "9.3.0" %}
{% set libgfortran_version = "5.0.0" %}
{% set max_libgfortran_version = "6.0.0.a0" %}
{% set libgfortran_major_version = "5" %}
{% set source_sha = "5258a9b6afe9463c2e56b9e8355b1a4bee125ca828b8078f910303bc2ef91fa6" %}
{% set url = "https://ftp.gnu.org/gnu/gcc/gcc-9.3.0/gcc-9.3.0.tar.gz" %}
{% endif %}

{% if gfortran_version == "10.2.1" %}
{% set libgfortran_version = "5.0.0" %}
{% set max_libgfortran_version = "6.0.0.a0" %}
{% set libgfortran_major_version = "5" %}
{% set source_sha = "ee3630fbe78cbf6c1f820700ecaedf92482c0cc72c77924acdebb8308cbf5d88" %}
{% set url = "https://github.com/fxcoudert/gcc/archive/81a488d83ac6216835ef36d51cea1ae567464016.tar.gz" %}
{% endif %}

{% if gfortran_version == "11.0.1" %}
{% set libgfortran_version = "5.0.0" %}
{% set version_suffix = ".dev0" %}
{% set max_libgfortran_version = "6.0.0.a0" %}
{% set libgfortran_major_version = "5" %}
{% set source_sha = "6b20738e5fac3933456829b67eb3e89bde7f42ef7d649ee67ba8240420372632" %}
{% set url = "https://github.com/iains/gcc-darwin-arm64/archive/bd796f1b0d4f8ff170ce51831916e9038dd8b1b9.tar.gz" %}
{% endif %}

{% if gfortran_version == "11.1.0" %}
{% set libgfortran_version = "5.0.0" %}
{% set max_libgfortran_version = "6.0.0.a0" %}
{% set libgfortran_major_version = "5" %}
{% set source_sha = "ce862b4a4bdc8f36c9240736d23cd625a48af82c2332d2915df0e16e1609a74c" %}
{% set url = "https://github.com/fxcoudert/gcc/archive/refs/tags/gcc-11.1.0-arm-20210504.tar.gz" %}
{% endif %}

package:
  name: gfortran_impl_{{ cross_target_platform }}
  version: {{ gfortran_version }}{{ version_suffix }}

source:
  url: {{ url }}
  sha256: {{ source_sha }}
  patches:
    - libgcc_macosx_min_version.patch  # [gfortran_version in ("7.5.0", "9.3.0")]

build:
  number: {{ build_number }}
  skip: True  # [win]
  skip: True  # [gfortran_version in ("11.1.0", "11.0.1", "10.2.1") and cross_target_platform != "osx-arm64"]
  skip: True  # [gfortran_version not in ("11.1.0", "11.0.1", "10.2.1") and (cross_target_platform == "osx-arm64" or target_platform == "osx-arm64")]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - flex
    - bison
    - sed
    - gawk
    - libtool   # [unix]
    - automake
    - autoconf
    - libiconv  # [build_platform != target_platform]
    - zlib      # [build_platform != target_platform]
    - gmp       # [build_platform != target_platform]
    - mpfr      # [build_platform != target_platform]
    - isl       # [build_platform != target_platform]
    - mpc       # [build_platform != target_platform]
  host:
    - libiconv
    - zlib
    - gmp
    - mpfr
    - isl
    - mpc
    - zstd
test:
  files:
    - hello.f90
    - maths.f90
    - omp-threadprivate.f90
    - gfortran_test.sh
  commands:
    - set -ex
    - export target_platform={{ target_platform }}
    - export cross_target_platform={{ cross_target_platform }}
    - bash gfortran_test.sh

outputs:
  - name: libgfortran-devel_{{ target_platform }}
    version: {{ gfortran_version }}{{ version_suffix }}
    build:
      skip: True  # [target_platform != cross_target_platform]
      skip: True  # [gfortran_version in ("11.1.0", "11.0.1", "10.2.1") and cross_target_platform != "osx-arm64"]
      skip: True  # [gfortran_version not in ("11.1.0", "11.0.1", "10.2.1") and (cross_target_platform == "osx-arm64" or target_platform == "osx-arm64")]
 
      noarch: generic
    files:
      # these are not generated for the cross compiler
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libgomp.spec
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libgfortran.spec
      # fortran module files
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/**
      # Static libraries and object files
      #- lib/gcc/{{ chost }}/{{ gfortran_version }}/libgomp.a
      #- lib/gcc/{{ chost }}/{{ gfortran_version }}/libgfortran.a
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libgcc.a
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libemutls_w.a
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libgcc_eh.a
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/crtfastmath.o
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/crt3.o
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/d10-uwfef.o
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/crttms.o
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/crttme.o
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libgcov.a
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libcaf_single.a

    test:
      commands:
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/libgomp.spec"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/libgfortran.spec"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/openacc_lib.h"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/openacc.f90"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/openacc.mod"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/omp_lib.h"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/omp_lib.f90"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/omp_lib.mod"
        - test -f "${PREFIX}/lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/ieee_features.mod"

  - name: gfortran_impl_{{ cross_target_platform }}
    version: {{ gfortran_version }}{{ version_suffix }}
    build:
      activate_in_script: True
      skip: True  # [win]
      skip: True  # [gfortran_version in ("11.1.0", "11.0.1", "10.2.1") and cross_target_platform != "osx-arm64"]
      skip: True  # [gfortran_version not in ("11.1.0", "11.0.1", "10.2.1") and (cross_target_platform == "osx-arm64" or target_platform == "osx-arm64")]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
        - flex
        - bison
        - sed
        - gawk
        - libtool # [unix]
        - automake
        - autoconf
        - libiconv  # [build_platform != target_platform]
        - zlib      # [build_platform != target_platform]
        - gmp       # [build_platform != target_platform]
        - mpfr      # [build_platform != target_platform]
        - isl       # [build_platform != target_platform]
        - mpc       # [build_platform != target_platform]
      host:
        - libiconv
        - zlib
        - gmp
        - mpfr
        - isl
        - mpc
        - zstd
      run:
        - libgfortran{{ libgfortran_major_version }} >={{ gfortran_version }}{{ version_suffix }}  # [target_platform == cross_target_platform]
        - libgfortran-devel_{{ target_platform }} {{ gfortran_version }}{{ version_suffix }}       # [target_platform == cross_target_platform]
        - isl
        - mpfr
        - mpc
        - gmp
        - zlib
        - libiconv
        - zstd
    files:
      - bin/gfortran   # [target_platform == cross_target_platform]
      - bin/{{ chost }}-gfortran

      - libexec/gcc/{{ chost }}/{{ gfortran_version }}/collect2
      - libexec/gcc/{{ chost }}/{{ gfortran_version }}/f951
      - libexec/gcc/{{ chost }}/{{ gfortran_version }}/lto-wrapper
      - libexec/gcc/{{ chost }}/{{ gfortran_version }}/cc1
      - lib/libgfortran.spec

      # For -fopenmp
      - lib/libgomp.spec

      # For -static
      - lib/libgfortran.a
      - lib/libgomp.a

      # include{,-fixed} may not be needed unless -fopenmp is passed (not sure on that)
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/include-fixed/**
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/include/**

      # Stub libraries
      - lib/libgcc_ext.10.4.dylib
      - lib/libgcc_ext.10.5.dylib


  - name: libgfortran
    version: {{ libgfortran_version }}{{ version_suffix }}
    target: {{ cross_target_platform }}
    build:
      skip: True  # [target_platform != cross_target_platform]
      skip: True  # [gfortran_version in ("11.1.0", "11.0.1", "10.2.1") and cross_target_platform != "osx-arm64"]
      skip: True  # [gfortran_version not in ("11.1.0", "11.0.1", "10.2.1") and (cross_target_platform == "osx-arm64" or target_platform == "osx-arm64")]
      string: {{ gfortran_version.replace(".", "_") }}_h{{ PKG_HASH }}_{{ build_number }}
    requirements:
      run:
        - libgfortran{{ libgfortran_major_version }}

  - name: libgfortran{{ libgfortran_major_version }}
    version: {{ gfortran_version }}{{ version_suffix }}
    target: {{ cross_target_platform }}
    build:
      skip: True  # [target_platform != cross_target_platform]
      skip: True  # [gfortran_version in ("11.1.0", "11.0.1", "10.2.1") and cross_target_platform != "osx-arm64"]
      skip: True  # [gfortran_version not in ("11.1.0", "11.0.1", "10.2.1") and (cross_target_platform == "osx-arm64" or target_platform == "osx-arm64")]
      run_exports:
        - libgfortran{{ libgfortran_major_version }} >={{ gfortran_version }}{{ version_suffix }}
    files:
      - lib/libgfortran.dylib
      - lib/libgfortran.{{ libgfortran_major_version }}.dylib
      - lib/libgomp.dylib
      - lib/libgomp.1.dylib

      # Including libquadmath for the time
      # being. This will need to be broken
      # out in the long term.
      - lib/libquadmath.dylib   # [not (osx and arm64)]
      - lib/libquadmath.0.dylib  # [not (osx and arm64)]

      # Including libgcc_s for the time
      # being. This will need to be broken
      # out in the long term.
      - lib/libgcc_s.1.dylib            # [cross_target_platform == "osx-64"]
      - lib/libgcc_s.1.1.dylib          # [cross_target_platform == "osx-arm64"]
      - lib/libgcc_s_ppc64.1.dylib      # [cross_target_platform == "osx-64"]
      - lib/libgcc_s_x86_64.1.dylib     # [cross_target_platform == "osx-64"]
      - lib/libgcc_s.dylib            # [cross_target_platform == "osx-arm64"]

    requirements:
      run:
        - llvm-openmp >=8.0.0
      run_constrained:
        - libgfortran {{ libgfortran_version }}{{ version_suffix }} *_{{ build_number }}

    test:
      commands:
        - test -f "${PREFIX}/lib/libgfortran.dylib"
        - test -f "${PREFIX}/lib/libgfortran.{{ libgfortran_major_version }}.dylib"

        - test -f "${PREFIX}/lib/libgomp.dylib"
        - test -f "${PREFIX}/lib/libgomp.1.dylib"

        # there is no quadmath support on arm ...
        - test -f "${PREFIX}/lib/libquadmath.dylib"    # [not (osx and arm64)]
        - test -f "${PREFIX}/lib/libquadmath.0.dylib"  # [not (osx and arm64)]

        - test -f "${PREFIX}/lib/libgcc_s.1.dylib"          # [cross_target_platform == "osx-64"]
        - test -f "${PREFIX}/lib/libgcc_s_ppc64.1.dylib"    # [cross_target_platform == "osx-64"]
        - test -f "${PREFIX}/lib/libgcc_s_x86_64.1.dylib"   # [cross_target_platform == "osx-64"]

        - test -f "${PREFIX}/lib/libgcc_s.1.1.dylib"          # [cross_target_platform == "osx-arm64"]

about:
  home: http://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  license_family: GPL
  license_file: COPYING3
  summary: Fortran compiler and libraries from the GNU Compiler Collection

extra:
  recipe-maintainers:
    - beckermr
    - isuruf
