conda_forge_output_validation: true
provider:
  linux_ppc64le: default
  linux_aarch64: default
travis:
  osx_image: xcode6.4
build_platform:
  osx_arm64: osx_64
test_on_native_only: true
build_with_mambabuild: false
github:
  branch_name: main
  tooling_branch_name: main
